---
- name: Open tcp ports
  iptables_raw:
    name: "iptables_open_tcp_port_{{ item }}"
    rules: |
      -A INPUT -p tcp -m tcp --dport {{ item }} -j ACCEPT
    state: present
    weight: 40
    ipversion: 4
    table: filter
  with_items: "{{ tcp_ports_to_open }}"
  when: tcp_ports_to_open is defined

- name: Open udp ports
  iptables_raw:
    name: "iptables_open_udp_port_{{ item }}"
    rules: |
      -A INPUT -p tcp -m udp --dport {{ item }} -j ACCEPT
    state: present
    weight: 40
    ipversion: 4
    table: filter
  with_items: "{{ udp_ports_to_open }}"
  when: udp_ports_to_open is defined

- name: Set custom iptables rules
  iptables_raw:
    name: 'iptables_custom_rules_{{ item.name }}'
    rules: '{{ item.rules }}'
    state: '{{ item.state }}'
    weight: '{{ item.weight|default(omit) }}'
    table: '{{ item.table|default(omit) }}'
  with_items: '{{ iptables_custom_rules }}'
  when: iptables_custom_rules is defined

- name: Set default iptables head rules
  iptables_raw:
    name: iptables_default_head
    weight: 10
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: '{{ iptables_default_head }}'
  when: iptables_default_head is defined

- name: Set default iptables tail rules
  iptables_raw:
    name: iptables_default_tail
    weight: 99
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_default_tail != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_default_tail }}'
  when: iptables_default_tail is defined
